apiVersion: v1
kind: Pod
metadata:
  name: kiada-ssl
spec:
  volumes:
  - name: etc-envoy
    projected:
      sources:
      - configMap:
          name: kiada-envoy-config

      - secret: kiada-tls
        items:
        - key: tls.crt
          path: example-com.crt
        - key: tls.key
          path: example-com.key
  
  containers:
  - name: kiada
    image: luksa/kiada:0.4
    ports:
    - name: http
      containerPort: 8080

  - name: envoy
    image: envoyproxy/envoy:v1.14.1
    ports:
    - name: https
      containerPort: 8443
    - name: admin
      containerPort: 9901
    volumeMounts:
    - name: etc-envoy
      mountPath: /etc/envoy