apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quiz-data-no-standard
spec:
  storageClassName: no-standard
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
