apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quiz-data
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""     # To bind a pre-provisioned persistent volume to this claim instead of provisioning a new one.
  accessModes:
  - ReadWriteOnce
  volumeName: quiz-data